<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('services')->insert([
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b40',
                'service_name' => 'nail mạ vàng',
                'description' => 'đính vàng 24k',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1zwGnED7B8_t375M0eNQgaV3a7Yzzoyvq',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b41',
                'service_name' => 'nail mạ kim cuong',
                'description' => 'đính vàng 24k',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1ufRk7ShJa7X2hCSEgQeGE4fCI5xWDe6R',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b42',
                'service_name' => 'nail mạ đồng',
                'description' => 'đính vàng 24k',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1bmWlISYFpkd17gK8riiLwWINXSlurkGj',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b43',
                'service_name' => 'nail bình thường',
                'description' => 'đính vàng 24k',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1txrTaHH4-F7YO_4I8eCoXwDHxxa0xOcS',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b44',
                'service_name' => 'nail mạ vàng rồng',
                'description' => 'đính vàng hôn',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1TMAkvaLCveMKsQ9D8L0ZPf8gPrnVGEoK',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b45',
                'service_name' => 'nail mạ vàng khổi',
                'description' => 'đính vàng thôi',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1zxTtCNkx59F5Eo91GEcNPb0WGXHRuGGB',
                'store_id' => '22222223',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b46',
                'service_name' => 'nail mạ vàng mã',
                'description' => 'đính vàng mà',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1YDN_CyEpN7DQAP9LbyRw8dQPvH5RQ92_',
                'store_id' => '22222224',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'service_name' => 'nail mạ vàng giả',
                'description' => 'đính vàng đó',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1bjBmWUAt3vGU97eHk869ncpoBKPwFStU',
                'store_id' => '22222224',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b48',
                'service_name' => 'nail mạ vàng vàng',
                'description' => 'đính vàng rồi',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1uQaEapG1Ly-8F-Ub3UgflH5QKMFBmAWQ',
                'store_id' => '22222224',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b49',
                'service_name' => 'nail mạ vàng 100k',
                'description' => 'đính vàng ưu',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1uF40ypUrMOLfd9TtPFf5qk2BXZk6yjTY',
                'store_id' => '22222224',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53b50',
                'service_name' => 'nail mạ vàng 1k',
                'description' => 'đính vàng hà',
                'price' => 10000000,
                'reduced_price' => 0,
                'image' => 'https://drive.google.com/uc?export=view&id=1in4hHG1JqUUw-MoQrFuRGtkHFVGCx8xY',
                'store_id' => '22222224',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53151',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1ZDukqWl9ietd2PdZnRWEK1Mp7VRsBkbk',
                'store_id' => '22222245',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53152',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1s8-t7Pl8KqpeByplCdUv4yrS192stRx8',
                'store_id' => '22222245',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53153',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1nBxH_c-Qb9sasqYvFYE2GRsGsE8R_FpC',
                'store_id' => '22222245',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53154',
                'service_name' => 'Chăm sóc và nối móng gel, nhũ, xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1YRk_Q0CbsyPIK5Fj4IK5TyPYbQ_yzYGg',
                'store_id' => '22222245',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53155',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1Q2qiW4kXtYbEGRPIgGTPKDxF1vXHzSjd',
                'store_id' => '22222245',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53156',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1FU98naEgy4Lii6kTB4MGJFuw7OzVkvSK',
                'store_id' => '22222246',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53157',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1O7Vi5GrNdiqehtQjhbtaE0rtRxOnQj-x',
                'store_id' => '22222246',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53158',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1KETL5Uyi7amlOan9hw5ndkuWPA1U-Qv4',
                'store_id' => '22222246',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53159',
                'service_name' => 'Chăm sóc và nối móng gel, nhũ, xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1PIR6fnHbhA9aGqh5wlhUP2MXA0J0SyNo',
                'store_id' => '22222246',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53160',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1BWl7dfy6iYJ4HULGVjPW3gAFqZaaaeN6',
                'store_id' => '22222246',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53161',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1RSV7AG5-wd4l0f6CcpJCJLRl9HSn9PDC',
                'store_id' => '22222247',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53162',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1bPkUugzeuygW3-MrdoDuKymor3yJLh87',
                'store_id' => '22222247',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53163',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1oA5t-2QbXbBAghx1qreVcGuBPY5j-e28',
                'store_id' => '22222247',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53164',
                'service_name' => 'Chăm sóc và nối móng gel, nhũ, xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1TcWkngky-6a41rYObx7eDPlydnTWnQLZ',
                'store_id' => '22222247',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53165',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1OjJGbsIHJKU1u3FSMwwxmPwWo1MdD4A5',
                'store_id' => '22222247',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53166',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1vvi8JVt_lUde8IxEHoCYzbDxWh0apAky',
                'store_id' => '22222248',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53167',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1R_dPG8QSoguu1hUcWQDxnvrEtf0GX-UA',
                'store_id' => '22222248',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53168',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=12pMJxcTfZ1fpfHhg21qJavuP_zqm0D0b',
                'store_id' => '22222248',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53169',
                'service_name' => 'Chăm sóc và nối móng gel, nhũ, xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=12O--YRR0QM7-QEnRu4hlewcC5t7RJlsO',
                'store_id' => '22222248',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53170',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=16763oSk_ujGcluW_JBBWat6N5Euppmpa',
                'store_id' => '22222248',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53171',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1ZX_jnJWHBQiGNNUR6ZDQLb7iYm5XiHON',
                'store_id' => '22222249',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53172',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1gDr3sYX55HPNoecCqUIdNbb6qO5rx9i3',
                'store_id' => '22222249',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53173',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1_npCf3vU4pKi-q0wToI5K77AUBmHB5fh',
                'store_id' => '22222249',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53174',
                'service_name' => 'Chăm sóc và nối móng gel, nhũ, xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=13QhzgpwfkQX0tW59eDfGLKX1byliiNi7',
                'store_id' => '22222249',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53175',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1ph9qVKO6WQscI24wm7aD-O4JUIW5mKnc',
                'store_id' => '22222249',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53275',
                'service_name' => 'Gel loang, gel nứt, gel nhũ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1ZuNBh6S3MXhEB7zlU5tNOe45_xxDfeme',
                'store_id' => '22222250',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53176',
                'service_name' => 'Chăm sóc và nối móng bột, vẽ gel',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 17000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1BT3cYiZ2PWMaOUbbzNpJytfBteNZdaDS',
                'store_id' => '22222250',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53177',
                'service_name' => 'Đính đá Úc tròn loại S10 AB xà cừ',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1P7rgyw0eK1MtpgOAiUCTmyw83ndn5g2g',
                'store_id' => '22222250',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53178',
                'service_name' => 'Đắp móng bột, tùy theo dạng đắp bột móng tay',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=1dwseuw6m6MXVyYXroXbuwQ8yc9B-PUpJ',
                'store_id' => '22222250',
            ],
            [
                'service_id' => '3891672d-1362-49a6-b986-81eaead53179',
                'service_name' => 'Vẽ cọ bản 3D, vẽ màu nước cao cấp',
                'description' => 'Quý khách sẽ có một bộ sản phẩm đẹp và ưng ý nhất, xứng đáng nhất với những gì mình bỏ ra',
                'reduced_price' => 0,
                'price' => 15000000.00,
                'image' => 'https://drive.google.com/uc?export=view&id=18xmVSlgnzmfTRKEefmJNE7-tlU4uTZYg',
                'store_id' => '22222250',
            ]
        ]);
    }
}
