<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class StoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stores')->insert([
            [
                'store_id' => 22222223,
                'store_name' => 'Mai nail',
                'phone' => '0967258000',
                'email' => 'phuchung2399@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '50 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '8:00:00',
                'close_time' => '21:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 4,
                'point_search' => 2,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222224,
                'store_name' => 'Diệu Nail',
                'phone' => '0967258111',
                'email' => 'hung.vo@student.passerellesnumeriques.org',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '51 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 4,
                'point_search' => 2,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222225,
                'store_name' => 'Tuấn Nail',
                'phone' => '0967258222',
                'email' => 'hung.vo1@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '52 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 2,
                'point_search' => 2,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222226,
                'store_name' => 'Thịnh Nail',
                'phone' => '0967258333',
                'email' => 'hung.vo2@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '53 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 1,
                'point_search' => 2,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222227,
                'store_name' => 'Sơn Trà Nail',
                'phone' => '0967258444',
                'email' => 'hung.vo3@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '54 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 1,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222228,
                'store_name' => 'Hải Châu nail',
                'phone' => '0967258555',
                'email' => 'hung.vo4@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '55 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222229,
                'store_name' => 'Ngũ Hành Sơn Nail',
                'phone' => '0967258666',
                'email' => 'hung.vo5@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '56 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 222222230,
                'store_name' => 'Cẩm Lệ Nail',
                'phone' => '0967258999',
                'email' => 'hung.vo6@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '57 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222231,
                'store_name' => 'Liên Chiểu Nail',
                'phone' => '0967258888',
                'email' => 'hung.vo7@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '58 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222232,
                'store_name' => 'An Hải Đông Nail',
                'phone' => '0967258777',
                'email' => 'hung.vo8@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '59 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222233,
                'store_name' => 'An Hải Bắc Nail',
                'phone' => '0967258778',
                'email' => 'hung.vo9@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '60 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 2,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222234,
                'store_name' => 'An Hải Tây Nail',
                'phone' => '0967258779',
                'email' => 'hung.vo10@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '62 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 2,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222235,
                'store_name' => 'An Hải Nam Nail',
                'phone' => '0967258780',
                'email' => 'hung.vo11@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '63 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222236,
                'store_name' => 'An Hải Trung Nail',
                'phone' => '0967258781',
                'email' => 'hung.vo12@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '64 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222237,
                'store_name' => 'An Trung Đông Nail',
                'phone' => '0967258782',
                'email' => 'hung.vo13@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '65 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222238,
                'store_name' => 'An Trung Tây Nail',
                'phone' => '0967258783',
                'email' => 'hung.vo14@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '80 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222239,
                'store_name' => 'An Trung Bắc Nail',
                'phone' => '0967258784',
                'email' => 'hung.vo15@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '81 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222240,
                'store_name' => 'Love Nail',
                'phone' => '0967258785',
                'email' => 'hung.vo16@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '82 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 2,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222241,
                'store_name' => 'Đại Chiến Nail',
                'phone' => '0967258786',
                'email' => 'hung.vo17@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '83 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222242,
                'store_name' => 'Dell Nail',
                'phone' => '0967258787',
                'email' => 'hung.vo18@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '84 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 0,
                'point_search' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ],
            [
                'store_id' => 22222243,
                'store_name' => 'HP Nail',
                'phone' => '0967258788',
                'email' => 'hung.vo19@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '85 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 0,
                'point_search' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222244,
                'store_name' => 'Iphone Nail',
                'phone' => '0967258789',
                'email' => 'hung.vo20@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '86 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 0,
                'point_search' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222245,
                'store_name' => 'Xiaomi Nail',
                'phone' => '0967258790',
                'email' => 'hung.vo21@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '87 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 1,
                'point_search' => 0,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222246,
                'store_name' => 'Oppo Nail',
                'phone' => '0967258791',
                'email' => 'hung.vo22@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '88 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222247,
                'store_name' => 'Samsung Nail',
                'phone' => '0967258792',
                'email' => 'hung.vo23@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '89 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 1,
                'point_search' => 0,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222248,
                'store_name' => 'Vivo Nail',
                'phone' => '0967258793',
                'email' => 'hung.vo24@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '90 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222249,
                'store_name' => 'Fly Nail',
                'phone' => '0967258794',
                'email' => 'hung.vo25@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '91 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 1,
                'point_search' => 0,
                'created_at' => new DateTime,
                'updated_at' => new DateTime
            ], [
                'store_id' => 22222250,
                'store_name' => 'Key Nail',
                'phone' => '0967258795',
                'email' => 'hung.vo26@gmail.com',
                'password' => '$2y$10$E1Xmh/fFgFXu8xFAGwJ4g.EOJaMCotQSIlXaqM68JRZE.0YS0LaQa',
                'address' => '92 Lê Hữu Trác, Phước Mỹ, Sơn Trà, Đà Nẵng',
                'open_time' => '9:00:00',
                'close_time' => '22:00:00',
                'image' => 'https://drive.google.com/uc?export=view&id=1dA1kJAywQVeGOABx7-tMbbmzv0VQj2sH',
                'status' => '',
                'location_id' => '3891672d-1362-49a6-b986-81eaead53b47',
                'auth' => 'store',
                'star' => 3,
                'point_search' => 0,
                'created_at' => '2020-07-27 06:24:50',
                'updated_at' => new DateTime
            ]
        ]);
    }
}
