//Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Get new stores
export const GET_NEW_STORE = 'GET_NEW_STORE';
export const GET_NEW_STORE_SUCCESS = 'GET_NEW_STORE_SUCCESS';
export const GET_NEW_STORE_FAILURE = 'GET_NEW_STORE_FAILURE';

//Get stores by star
export const GET_STORE_BY_STAR = 'GET_STORE_BY_STAR';
export const GET_STORE_BY_STAR_SUCCESS = 'GET_STORE_BY_STAR_SUCCESS';
export const GET_STORE_BY_STAR_FAILURE = 'GET_STORE_BY_STAR_FAILURE';

//Get store detail
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';
export const GET_STORE_DETAIL_SUCCESS = 'GET_STORE_DETAIL_SUCCESS';
export const GET_STORE_DETAIL_FAILURE = 'GET_STORE_DETAIL_FAILURE';

//Get store services
export const GET_STORE_SERVICES = 'GET_STORE_SERVICES';
export const GET_STORE_SERVICES_SUCCESS = 'GET_STORE_SERVICES_SUCCESS';
export const GET_STORE_SERVICES_FAILURE = 'GET_STORE_SERVICES_FAILURE';

//Get all services
export const GET_ALL_SERVICES = 'GET_All_SERVICES';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAILURE = 'GET_ALL_SERVICES_FAILURE';

//Get all slide
export const GET_ALL_SLIDE = 'GET_ALL_SLIDE';
export const GET_ALL_SLIDE_SUCCESS = 'GET_ALL_SLIDE_SUCCESS';
export const GET_ALL_SLIDE_FAILURE = 'GET_ALL_SLIDE_FAILURE';

// Get all comments of a store
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';
export const GET_ALL_COMMENT_FAILURE = 'GET_ALL_COMMENT_FAILURE';

// Create comment
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

// Update comment
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE';

// Get notifications of user
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAILURE = 'GET_NOTIFICATION_FAILURE';

// Get all orders of user
export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAILURE = 'GET_ALL_ORDER_FAILURE';

// Get all orders detail
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE';

// Cancel order
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

// Add cart item
export const ADD_CART = 'ADD_CART';
export const DELETE_ALL_CART = 'DELETE_ALL_CART';
export const DELETE_CART = 'DELETE_CART';
export const ADD_STORE_ID = 'ADD_STORE_ID';
export const DELETE_STORE_ID = 'DELETE_STORE_ID';

// Get all vouchers
export const GET_ALL_VOUCHERS = 'GET_ALL_VOUCHERS';
export const GET_ALL_VOUCHERS_SUCCESS = 'GET_ALL_VOUCHERS_SUCCESS';
export const GET_ALL_VOUCHERS_FAILURE = 'GET_ALL_VOUCHERS_FAILURE';

// Total apply voucher
export const APPLY_VOUCHER = 'APPLY_VOUCHER';
export const APPLY_VOUCHER_SUCCESS = 'APPLY_VOUCHER_SUCCESS';
export const APPLY_VOUCHER_FAILURE = 'APPLY_VOUCHER_FAILURE';

// Search stores
export const SEARCH_STORE = 'SEARCH_STORE';
export const SEARCH_STORE_SUCCESS = 'SEARCH_STORE_SUCCESS';
export const SEARCH_STORE_FAILURE = 'SEARCH_STORE_FAILURE';

// Add cart item
export const ADD_KEY = 'ADD_KEY';
export const DELETE_KEY = 'DELETE_KEY';

// Get all stores exist
export const GET_ALL_STORE = 'GET_ALL_STORE';
export const GET_ALL_STORE_SUCCESS = 'GET_ALL_STORE_SUCCESS';
export const GET_ALL_STORE_FAILURE = 'GET_ALL_STORE_FAILURE';
