// Register
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

//Login
export const LOG_IN = 'LOG_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Get new stores
export const GET_NEW_STORE = 'GET_NEW_STORE';
export const GET_NEW_STORE_SUCCESS = 'GET_NEW_STORE_SUCCESS';
export const GET_NEW_STORE_FAILURE = 'GET_NEW_STORE_FAILURE';

//Get stores by star
export const GET_STORE_BY_STAR = 'GET_STORE_BY_STAR';
export const GET_STORE_BY_STAR_SUCCESS = 'GET_STORE_BY_STAR_SUCCESS';
export const GET_STORE_BY_STAR_FAILURE = 'GET_STORE_BY_STAR_FAILURE';

//Get store detail
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';
export const GET_STORE_DETAIL_SUCCESS = 'GET_STORE_DETAIL_SUCCESS';
export const GET_STORE_DETAIL_FAILURE = 'GET_STORE_DETAIL_FAILURE';

//Get store services
export const GET_STORE_SERVICES = 'GET_STORE_SERVICES';
export const GET_STORE_SERVICES_SUCCESS = 'GET_STORE_SERVICES_SUCCESS';
export const GET_STORE_SERVICES_FAILURE = 'GET_STORE_SERVICES_FAILURE';
